# Generated by Django 3.0.3 on 2020-03-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_items',
        ),
    ]
