# Generated by Django 3.0.3 on 2020-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0003_add_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_items',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='add_items',
            name='image2',
            field=models.FileField(default='none', upload_to='images'),
        ),
        migrations.AddField(
            model_name='add_items',
            name='image3',
            field=models.FileField(default='none', upload_to='images'),
        ),
        migrations.AddField(
            model_name='add_items',
            name='image4',
            field=models.FileField(default='none', upload_to='images'),
        ),
    ]
