# Generated by Django 3.0.3 on 2020-03-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0004_auto_20200311_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_items',
            name='image2',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='add_items',
            name='image3',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='add_items',
            name='image4',
            field=models.FileField(upload_to='images'),
        ),
    ]
