# Generated by Django 3.0.3 on 2020-03-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0006_remove_categories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='ordered_items',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='useraddress',
        ),
    ]
