# Generated by Django 3.0.3 on 2020-03-31 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hell', '0007_auto_20200331_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pno', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ordered_items',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('payment_type', models.CharField(default='null', max_length=20)),
                ('status', models.CharField(default='Payment pending', max_length=50)),
                ('shipping_status', models.CharField(default='Shipping pending', max_length=300)),
                ('delivery_status', models.CharField(default='Delivery pending', max_length=300)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hell.add_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hell.add_items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
