# Generated by Django 3.0.3 on 2020-04-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0008_cart_ordered_items_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='technician',
            fields=[
                ('complaint_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('contact', models.IntegerField(max_length=12)),
                ('category', models.CharField(max_length=50)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
