# Generated by Django 3.0.3 on 2020-04-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0009_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
