# Generated by Django 3.0.3 on 2020-05-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0011_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='technician',
        ),
    ]
