# Generated by Django 3.0.3 on 2020-05-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0015_special_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='special_items',
        ),
    ]
