# Generated by Django 3.0.3 on 2020-06-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0016_delete_special_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hell.add_items')),
            ],
        ),
    ]
