# Generated by Django 3.0.3 on 2020-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0019_auto_20200606_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
