# Generated by Django 3.0.3 on 2020-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0021_auto_20200616_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_items',
            name='name',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
