# Generated by Django 3.0.3 on 2020-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0022_ordered_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_items',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
