# Generated by Django 3.0.3 on 2020-09-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0023_auto_20200927_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_items',
            name='name',
        ),
    ]
