# Generated by Django 3.0.3 on 2020-10-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell', '0025_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactdetails',
        ),
    ]
