from django.contrib import admin
from django.urls import path
from .import views

urlpatterns = [
    path('',views.home,name="home"),
    path('index',views.index,name="index"),
    path('store',views.store,name="store"),
    path('checkout',views.checkout,name="checkout"),
    path('cart',views.viewcart,name="cart"),
    path('details',views.loadproduct,name="loadproduct"),
    path('acc',views.myaccount),
    path('signup',views.signup,name="signup"),
    path('login',views.login,name="login"),
    path('sign',views.sign,name="sign"),
    path('log',views.log,name="log"),
    path('about',views.about,name="about"),
    path('contact',views.contact,name="contact"),
    path('techpage',views.techpage,name="request technician"),
    path('addtocart',views.addtocart,name="cart"),
    path('viewcart',views.viewcart,name="viewcart"),
    path('delete',views.deletecartitem,name="removeitem"),
    path('delete1', views.deletecartitem1, name="removeitem"),
    path('tech',views.complaint,name="complaint"),
    path('wish',views.wish,name="wishlist"),
    path('addtowish',views.addtowish,name="wishlist"),
    path('deletewish',views.deletewishitem,name="wishlist"),
    path('wishtocart',views.wishtocart,name="wishlist"),
    path('confirm',views.confirm_order,name="checkout"),
    path('search',views.searchResult,name="category"),
    path('logout',views.logoutuser,name="logout"),
    path('asortname',views.ascsortby_name,name="category"),
    path('dsortname',views.dscsortby_name),
    path('asortprice',views.ascsortby_price),
    path('dsortprice',views.dscsortby_price),
    path('price_range',views.pricesort),
    path('trackorder',views.trackorder),
    path('trackcomp',views.trackcomplaint),
    path('category',views.category),
    path('review',views.reviewrate),
    path('bm',views.cat1,name="category"),
    path('sm',views.cat2,name="category"),
    path('fp',views.cat3,name="category"),
    path('jmg',views.cat4,name="category"),
    path('mo',views.cat5,name="category"),
    path('rm',views.cat6,name="category"),
    path('gt',views.cat7,name="category"),
    path('bc',views.cat8,name="category"),
    path('ck',views.cat9,name="category"),
    path('ckr',views.cat10,name="category"),
    path('k',views.cat11,name="category"),
    path('cm',views.cat12,name="category"),
    path('afdf',views.cat13,name="category"),
    path('wp',views.cat14,name="category"),
    path('cmn',views.cat15,name="category"),
    path('pm',views.cat16,name="category"),
    path('cro',views.cat17,name="category"),
    path('dec',views.cat18,name="category"),
    path('croc',views.crock,name="category"),
    path('deco',views.decor,name="category"),
    path('special',views.special,name="Special"),
    path('delcomp',views.deletecomplaint),
    path('delorder', views.deleteorder),
    path('contactus',views.contactus)

]